### ISSUE TITLE
Display "Latest Posts" module if blog url is set

### ISSUE THREAD

**Issue by epicmiller** [epicmiller/marchforscience#2]
Medium allows us to fetch the latest posts as JSON from the browser: https://medium.com/@bryantaxs/latest?format=json

Wordpress allows us to fetch posts as JSON using the following plugin:
https://wordpress.org/plugins/rest-api/
https://css-tricks.com/using-the-wp-api-to-fetch-posts/

Squarespace allows us to fetch posts as JSON from the browser:
https://www.marchforscience.com/blog?format=json

Create a "latest posts" module on the site that, if a blog URL is saved for the satellite, will display the last few blog posts. There will be a see all link that opens a new tab to the external blog.

**Comment by jameelahuq** [comment]
Right now, blog module exists and is harddcoded. It will only work for a medium blog atm.
Going to hard code some data for a square blog next.

<img width="611" alt="2017-04-17 12 34 09" src="https://cloud.githubusercontent.com/assets/9761692/25101822/9883c19c-236a-11e7-9d94-b32bfd2bd757.png">

**Comment by jameelahuq** [comment]
Squarespace and Wordpress v2 done :)
<img width="564" alt="2017-04-18 22 44 02" src="https://cloud.githubusercontent.com/assets/9761692/25165083/798c863c-2489-11e7-9eb5-4f566ed57be1.png">
