### ISSUE TITLE
redirect web form to Action Network

### ISSUE THREAD

**Issue by kategage** [epicmiller/marchforscience#23]
a new action has been set up in Action Network that allows people to sign up for the MFS email list and the website form needs to redirect there, or to the AN API

**Comment by rrbaker** [comment]
This is done, though not well or pretty.  Right now it's an iframe bringing in the HTML widget from AN.  How you doin', 2003 way of doing things.  Works, though we should go back to the old Ember generated form writing to the API.  Going to close this out an open a new ticket with those details.
