### ISSUE TITLE
redirect salem oregon page

### ISSUE THREAD

**Issue by kategage** [epicmiller/marchforscience#24]
the salem oregon page needs to direct to https://www.facebook.com/SalemOregonMarchForScience/

@jameelahuq @rrbaker @epicmiller @ichthyos  @Samkimsamkim  can one of you fix?

**Comment by kategage** [comment]
ok- interesting. We might need to do it in the database - hoping to get access to that

**Comment by rrbaker** [comment]
Correct, this is managed externally and changed.  See @kategage or @epicmiller for requests.
